[package]
name = "raytracing-compute"
version = "0.1.0"
edition = "2024"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[dependencies]
bytemuck = "1.24.0"
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.29"
